[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-recipe-ddd"
version = "0.1.0"
description = "FastAPI recipe example"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn",
    "watchfiles",
    "dijay",
]


[tool.setuptools]
packages = ["src"]

[tool.uv.sources]
dijay = { workspace = true }

[dependency-groups]
dev = [
    "uvicorn>=0.41.0",
]
