[project]
name = "dijay"
version = "0.1.0"
description = "Modern Async DI Container for Python 3.14+"
readme = "README.md"
requires-python = ">=3.14"
authors = [{ name = "Leandro Luk", email = "seu-email@exemplo.com" }]
keywords = ["dependency-injection", "async", "nestjs", "solid", "type-hints"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries",
]
dependencies = [
    "ruff>=0.15.1",
]

[project.urls]
Homepage = "https://github.com/leandroluk/dijay"
Repository = "https://github.com/leandroluk/dijay"
Issues = "https://github.com/leandroluk/dijay/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest>=8.0.0", "pytest-asyncio>=0.23.0", "ruff>=0.3.0", "mypy>=1.9.0"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
target-version = "py314"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "ASYNC", "S"]
ignore = ["S101"]                                 # Permite assert em testes

[tool.mypy]
python_version = "3.14"
strict = true
files = ["dijay"]
