[project]
site_name = "dijay"
site_description = "The 'remix' your architecture needs: NestJS-style modularity, native async performance, and rigorous typing for Python 3.14+."
site_url = "https://leandroluk.github.io/python-dijay/"
repo_url = "https://github.com/leandroluk/python-dijay"
repo_name = "leandroluk/python-dijay"

[project.theme]
name = "material"
favicon = "assets/logo.svg"
palette = [
    { scheme = "slate", primary = "deep purple", accent = "amber", toggle = { icon = "material/brightness-4", name = "Switch to light mode" } },
    { scheme = "default", primary = "deep purple", accent = "amber", toggle = { icon = "material/brightness-7", name = "Switch to dark mode" } },
]
features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.top",
    "content.code.copy",
    "content.code.annotate",
    "search.highlight",
]

[project.theme.icon]
logo = "lucide/headphones"
repo = "fontawesome/brands/github"

[plugins.mkdocstrings.handlers.python]
paths = ["."]
options = { show_source = true, show_root_heading = true, heading_level = 3 }

[[nav]]
Home = "index.md"

[[nav]]
"Getting Started" = "getting-started.md"

[[nav."Recipes"]]
Modules = "recipes/modules.md"

[[nav."Recipes"]]
Providers = "recipes/providers.md"

[[nav."Recipes"]]
Injection = "recipes/injection.md"

[[nav."Recipes"]]
"Lifecycle Hooks" = "recipes/lifecycle.md"

[[nav."Recipes"]]
"FastAPI Integration" = "recipes/fastapi.md"

[[nav]]
"API Reference" = "api.md"
